services:
    database:
        image: todolist-postgres:latest
        container_name: todolist-db
        shm_size: 128mb
        environment:
            POSTGRES_PASSWORD: q0M1d0X)uF[cg
            POSTGRES_USER: postgres
            POSTGRES_DB: todolist
        ports:
            - 5432:5432
        volumes:
            - pg_data:/var/lib/postgresql/data
volumes:
    pg_data:
